# Generated by Django 3.0.5 on 2020-04-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_activity_manager_throttle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throttle',
            name='manager',
        ),
        migrations.AddField(
            model_name='throttle',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Manager'),
        ),
    ]
