# Generated by Django 3.0.5 on 2020-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200404_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throttle',
            name='manager',
        ),
        migrations.AddField(
            model_name='throttle',
            name='manager',
            field=models.ManyToManyField(to='program.Manager'),
        ),
    ]
